#!/bin/sh

#$HOME/.config/bspwm/autostart.sh
xrandr --output HDMI-0 --primary --mode 1920x1080 --rotate normal --output DP-1 --mode 1920x1080 --rotate left --left-of HDMI-0 &
sxhkd &
polybar bar &
polybar bar_left &

# https://www.reddit.com/r/unixporn/comments/6c7nlx/question_how_to_assign_dual_monitor_wallpapers/
feh --bg-fill ~/walls/waterfall.jpg

bspc monitor HDMI-0 -d 1 2 3 4 
bspc monitor DP-1 -d 1 2 3 4
#bspc monitor DP-1 -d 4 5 6 7

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google-chrome desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
